### ISSUE TITLE
后台没有吗 ？

### ISSUE THREAD

**Issue by sunyjgithub** [F999999999/cloud-store#69]

**Comment by F999999999** [comment]
后台暂时没有开源的打算

**Comment by F999999999** [comment]
后端已开源，请查看[README.md](https://github.com/F999999999/cloud-store/blob/main/README.md)

**Comment by wukailing112113** [comment]
后端没有数据库呀大侠

**Comment by wukailing112113** [comment]
也启动不了，也不报错噢
终止批处理操作吗(Y/N)? y
(base) PS E:\科大讯飞\教学工作\竞赛\项目储备\可视化\cloud-store-serve-main> npm run dev

> cloud-store-serve@0.1.0 dev
> set NODE_ENV=development&&nodemon bin/www

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node bin/www`
